////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace Report.Api.Report {
    
//    public partial class DDEmployeeReport : DevExpress.XtraReports.UI.XtraReport {
//        private void InitializeComponent() {
//            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Report.Api.Report.DDEmployeeReport.repx");

//            // Controls
//            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
//            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
//            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
//            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
//            this.DetailReport2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailReportBand>("DetailReport2");
//            this.xrTable2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("xrTable2");
//            this.xrTableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("xrTableRow2");
//            this.FamilyName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("FamilyName");
//            this.GivenName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("GivenName");
//            this.MiddleName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("MiddleName");
//            this.Gender = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Gender");
//            this.StreetAddress1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("StreetAddress1");
//            this.Suburb = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Suburb");
//            this.State = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("State");
//            this.Postcode = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Postcode");
//            this.Birthdate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Birthdate");
//            this.StartDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("StartDate");
//            this.TerminationDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("TerminationDate");
//            this.HourlyRate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HourlyRate");
//            this.xrTableCell22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell22");
//            this.xrTableCell24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell24");
//            this.xrTableCell25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell25");
//            this.xrTableCell26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell26");
//            this.Occupation = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Occupation");
//            this.Location = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Location");
//            this.HECS = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("HECS");
//            this.Paym = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Paym");
//            this.Annu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Annu");
//            this.Long = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Long");
//            this.RDO = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("RDO");
//            this.EmployeeCode = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("EmployeeCode");
//            this.Status = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Status");
//            this.xrTableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell1");
//            this.xrTableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell4");
//            this.xrTableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell3");
//            this.xrTableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell5");
//            this.xrTableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell2");
//            this.xrTableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell7");
//            this.xrTableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell6");
//            this.xrTableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell8");
//            this.xrTableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell9");
//            this.xrTableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell10");
//            this.xrTableCell21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell21");
//            this.xrTableCell54 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell54");
//            this.Detail3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail3");
//            this.xrTable3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("xrTable3");
//            this.xrTableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("xrTableRow3");
//            this.xrTableCell27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell27");
//            this.xrTableCell29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell29");
//            this.xrTableCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell30");
//            this.xrTableCell31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell31");
//            this.xrTableCell32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell32");
//            this.xrTableCell33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell33");
//            this.xrTableCell34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell34");
//            this.xrTableCell35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell35");
//            this.xrTableCell36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell36");
//            this.xrTableCell37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell37");
//            this.xrTableCell38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell38");
//            this.xrTableCell39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell39");
//            this.xrTableCell40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell40");
//            this.xrTableCell41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell41");
//            this.xrTableCell42 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell42");
//            this.xrTableCell43 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell43");
//            this.xrTableCell44 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell44");
//            this.xrTableCell45 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell45");
//            this.xrTableCell46 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell46");
//            this.xrTableCell47 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell47");
//            this.xrTableCell48 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell48");
//            this.xrTableCell49 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell49");
//            this.xrTableCell50 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell50");
//            this.xrTableCell51 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell51");
//            this.xrTableCell52 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell52");
//            this.xrTableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell11");
//            this.xrTableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell16");
//            this.xrTableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell13");
//            this.xrTableCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell15");
//            this.xrTableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell14");
//            this.xrTableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell12");
//            this.xrTableCell20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell20");
//            this.xrTableCell18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell18");
//            this.xrTableCell17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell17");
//            this.xrTableCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell19");
//            this.xrTableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell28");
//            this.xrTableCell53 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("xrTableCell53");

//            // Calculated Fields
//            this.HECSCal = reportInitializer.GetCalculatedField("HECSCal");
//        }
//        private DevExpress.XtraReports.UI.DetailBand Detail;
//        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
//        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
//        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
//        private DevExpress.XtraReports.UI.DetailReportBand DetailReport2;
//        private DevExpress.XtraReports.UI.XRTable xrTable2;
//        private DevExpress.XtraReports.UI.XRTableRow xrTableRow2;
//        private DevExpress.XtraReports.UI.XRTableCell FamilyName;
//        private DevExpress.XtraReports.UI.XRTableCell GivenName;
//        private DevExpress.XtraReports.UI.XRTableCell MiddleName;
//        private DevExpress.XtraReports.UI.XRTableCell Gender;
//        private DevExpress.XtraReports.UI.XRTableCell StreetAddress1;
//        private DevExpress.XtraReports.UI.XRTableCell Suburb;
//        private DevExpress.XtraReports.UI.XRTableCell State;
//        private DevExpress.XtraReports.UI.XRTableCell Postcode;
//        private DevExpress.XtraReports.UI.XRTableCell Birthdate;
//        private DevExpress.XtraReports.UI.XRTableCell StartDate;
//        private DevExpress.XtraReports.UI.XRTableCell TerminationDate;
//        private DevExpress.XtraReports.UI.XRTableCell HourlyRate;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell22;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell24;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell25;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell26;
//        private DevExpress.XtraReports.UI.XRTableCell Occupation;
//        private DevExpress.XtraReports.UI.XRTableCell Location;
//        private DevExpress.XtraReports.UI.XRTableCell HECS;
//        private DevExpress.XtraReports.UI.XRTableCell Paym;
//        private DevExpress.XtraReports.UI.XRTableCell Annu;
//        private DevExpress.XtraReports.UI.XRTableCell Long;
//        private DevExpress.XtraReports.UI.XRTableCell RDO;
//        private DevExpress.XtraReports.UI.XRTableCell EmployeeCode;
//        private DevExpress.XtraReports.UI.XRTableCell Status;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell1;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell4;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell3;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell5;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell2;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell7;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell6;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell8;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell9;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell10;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell21;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell54;
//        private DevExpress.XtraReports.UI.DetailBand Detail3;
//        private DevExpress.XtraReports.UI.XRTable xrTable3;
//        private DevExpress.XtraReports.UI.XRTableRow xrTableRow3;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell27;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell29;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell30;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell31;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell32;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell33;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell34;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell35;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell36;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell37;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell38;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell39;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell40;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell41;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell42;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell43;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell44;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell45;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell46;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell47;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell48;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell49;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell50;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell51;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell52;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell11;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell16;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell13;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell15;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell14;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell12;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell20;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell18;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell17;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell19;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell28;
//        private DevExpress.XtraReports.UI.XRTableCell xrTableCell53;
//        private DevExpress.XtraReports.UI.CalculatedField HECSCal;
//    }
//}
