//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.DataAccess.ObjectBinding;
using Report.Api.Entity;

namespace Reporting.Designer {
    
    public partial class DDEmployeeReport : DevExpress.XtraReports.UI.XtraReport {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.Detail = new DevExpress.XtraReports.UI.DetailBand();
            this.TopMargin = new DevExpress.XtraReports.UI.TopMarginBand();
            this.BottomMargin = new DevExpress.XtraReports.UI.BottomMarginBand();
            this.GroupHeader1 = new DevExpress.XtraReports.UI.GroupHeaderBand();
            this.xrTable2 = new DevExpress.XtraReports.UI.XRTable();
            this.xrTableRow2 = new DevExpress.XtraReports.UI.XRTableRow();
            this.FamilyName = new DevExpress.XtraReports.UI.XRTableCell();
            this.GivenName = new DevExpress.XtraReports.UI.XRTableCell();
            this.MiddleName = new DevExpress.XtraReports.UI.XRTableCell();
            this.Gender = new DevExpress.XtraReports.UI.XRTableCell();
            this.StreetAddress1 = new DevExpress.XtraReports.UI.XRTableCell();
            this.Suburb = new DevExpress.XtraReports.UI.XRTableCell();
            this.State = new DevExpress.XtraReports.UI.XRTableCell();
            this.Postcode = new DevExpress.XtraReports.UI.XRTableCell();
            this.Birthdate = new DevExpress.XtraReports.UI.XRTableCell();
            this.StartDate = new DevExpress.XtraReports.UI.XRTableCell();
            this.TerminationDate = new DevExpress.XtraReports.UI.XRTableCell();
            this.HourlyRate = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell22 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell24 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell25 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell26 = new DevExpress.XtraReports.UI.XRTableCell();
            this.Occupation = new DevExpress.XtraReports.UI.XRTableCell();
            this.Location = new DevExpress.XtraReports.UI.XRTableCell();
            this.HECS = new DevExpress.XtraReports.UI.XRTableCell();
            this.Paym = new DevExpress.XtraReports.UI.XRTableCell();
            this.Annu = new DevExpress.XtraReports.UI.XRTableCell();
            this.Long = new DevExpress.XtraReports.UI.XRTableCell();
            this.RDO = new DevExpress.XtraReports.UI.XRTableCell();
            this.EmployeeCode = new DevExpress.XtraReports.UI.XRTableCell();
            this.Status = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell1 = new DevExpress.XtraReports.UI.XRTableCell();
            this.HideEmergencyContactDetails = new DevExpress.XtraReports.UI.FormattingRule();
            this.xrTableCell4 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell3 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell5 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell2 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell7 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell6 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell8 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell9 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell10 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell21 = new DevExpress.XtraReports.UI.XRTableCell();
            this.DetailReport2 = new DevExpress.XtraReports.UI.DetailReportBand();
            this.Detail3 = new DevExpress.XtraReports.UI.DetailBand();
            this.xrTable3 = new DevExpress.XtraReports.UI.XRTable();
            this.xrTableRow3 = new DevExpress.XtraReports.UI.XRTableRow();
            this.xrTableCell27 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell29 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell30 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell31 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell32 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell33 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell34 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell35 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell36 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell37 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell38 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell39 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell40 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell41 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell42 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell43 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell44 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell45 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell46 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell47 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell48 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell49 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell50 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell51 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell52 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell11 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell16 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell13 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell15 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell14 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell12 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell20 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell18 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell17 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell19 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell28 = new DevExpress.XtraReports.UI.XRTableCell();
            this.HECSCal = new DevExpress.XtraReports.UI.CalculatedField();
            this.HideEmergencyContactDetailsHeader = new DevExpress.XtraReports.UI.FormattingRule();
            this.xrTableCell54 = new DevExpress.XtraReports.UI.XRTableCell();
            this.xrTableCell53 = new DevExpress.XtraReports.UI.XRTableCell();
            this.DDEmploeeBinding = new ObjectDataSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.xrTable2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.xrTable3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DDEmploeeBinding)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // Detail
            // 
            this.Detail.Expanded = false;
            this.Detail.HeightF = 0F;
            this.Detail.Name = "Detail";
            this.Detail.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // TopMargin
            // 
            this.TopMargin.HeightF = 0F;
            this.TopMargin.Name = "TopMargin";
            this.TopMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // BottomMargin
            // 
            this.BottomMargin.HeightF = 0F;
            this.BottomMargin.Name = "BottomMargin";
            this.BottomMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // GroupHeader1
            // 
            this.GroupHeader1.Controls.AddRange(new DevExpress.XtraReports.UI.XRControl[] {
            this.xrTable2});
            this.GroupHeader1.HeightF = 25F;
            this.GroupHeader1.Name = "GroupHeader1";
            this.GroupHeader1.RepeatEveryPage = true;
            // 
            // xrTable2
            // 
            this.xrTable2.Font = new System.Drawing.Font("Arial", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.xrTable2.LocationFloat = new DevExpress.Utils.PointFloat(0F, 0F);
            this.xrTable2.Name = "xrTable2";
            this.xrTable2.Rows.AddRange(new DevExpress.XtraReports.UI.XRTableRow[] {
            this.xrTableRow2});
            this.xrTable2.SizeF = new System.Drawing.SizeF(2339F, 25F);
            this.xrTable2.StylePriority.UseBorders = false;
            this.xrTable2.StylePriority.UseFont = false;
            // 
            // xrTableRow2
            // 
            this.xrTableRow2.Cells.AddRange(new DevExpress.XtraReports.UI.XRTableCell[] {
            this.FamilyName,
            this.GivenName,
            this.MiddleName,
            this.Gender,
            this.StreetAddress1,
            this.Suburb,
            this.State,
            this.Postcode,
            this.Birthdate,
            this.StartDate,
            this.TerminationDate,
            this.HourlyRate,
            this.xrTableCell22,
            this.xrTableCell24,
            this.xrTableCell25,
            this.xrTableCell26,
            this.Occupation,
            this.Location,
            this.HECS,
            this.Paym,
            this.Annu,
            this.Long,
            this.RDO,
            this.EmployeeCode,
            this.Status,
            this.xrTableCell1,
            this.xrTableCell4,
            this.xrTableCell3,
            this.xrTableCell5,
            this.xrTableCell2,
            this.xrTableCell7,
            this.xrTableCell6,
            this.xrTableCell8,
            this.xrTableCell9,
            this.xrTableCell10,
            this.xrTableCell21,
            this.xrTableCell54});
            this.xrTableRow2.Name = "xrTableRow2";
            this.xrTableRow2.Weight = 1D;
            // 
            // FamilyName
            // 
            this.FamilyName.Name = "FamilyName";
            this.FamilyName.Text = "Family Name";
            this.FamilyName.Weight = 0.1303226814789534D;
            this.FamilyName.WordWrap = false;
            // 
            // GivenName
            // 
            this.GivenName.Name = "GivenName";
            this.GivenName.Text = "Given Name";
            this.GivenName.Weight = 0.10297821631115781D;
            this.GivenName.WordWrap = false;
            // 
            // MiddleName
            // 
            this.MiddleName.Name = "MiddleName";
            this.MiddleName.Text = "Middle Name";
            this.MiddleName.Weight = 0.13056754075991034D;
            this.MiddleName.WordWrap = false;
            // 
            // Gender
            // 
            this.Gender.Name = "Gender";
            this.Gender.Text = "Gender";
            this.Gender.Weight = 0.13962006862828374D;
            this.Gender.WordWrap = false;
            // 
            // StreetAddress1
            // 
            this.StreetAddress1.Name = "StreetAddress1";
            this.StreetAddress1.Text = "Street";
            this.StreetAddress1.Weight = 0.10638827846359678D;
            this.StreetAddress1.WordWrap = false;
            // 
            // Suburb
            // 
            this.Suburb.Name = "Suburb";
            this.Suburb.Text = "Suburb";
            this.Suburb.Weight = 0.1370416292336557D;
            this.Suburb.WordWrap = false;
            // 
            // State
            // 
            this.State.Name = "State";
            this.State.Text = "State ";
            this.State.Weight = 0.099821150721146945D;
            this.State.WordWrap = false;
            // 
            // Postcode
            // 
            this.Postcode.Name = "Postcode";
            this.Postcode.Text = "Postcode";
            this.Postcode.Weight = 0.17470662945167087D;
            this.Postcode.WordWrap = false;
            // 
            // Birthdate
            // 
            this.Birthdate.Name = "Birthdate";
            this.Birthdate.Text = "Birthdate";
            this.Birthdate.Weight = 0.09164078842012742D;
            this.Birthdate.WordWrap = false;
            // 
            // StartDate
            // 
            this.StartDate.Name = "StartDate";
            this.StartDate.Text = "Start Date";
            this.StartDate.Weight = 0.093778506442438181D;
            this.StartDate.WordWrap = false;
            // 
            // TerminationDate
            // 
            this.TerminationDate.Name = "TerminationDate";
            this.TerminationDate.Text = "Termination Date";
            this.TerminationDate.Weight = 0.14801809809302796D;
            this.TerminationDate.WordWrap = false;
            // 
            // HourlyRate
            // 
            this.HourlyRate.Name = "HourlyRate";
            this.HourlyRate.StylePriority.UseTextAlignment = false;
            this.HourlyRate.Text = "Hourly Rate";
            this.HourlyRate.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            this.HourlyRate.Weight = 0.1248123432026309D;
            this.HourlyRate.WordWrap = false;
            // 
            // xrTableCell22
            // 
            this.xrTableCell22.Name = "xrTableCell22";
            this.xrTableCell22.Text = "Payment Group";
            this.xrTableCell22.Weight = 0.14662596011379012D;
            this.xrTableCell22.WordWrap = false;
            // 
            // xrTableCell24
            // 
            this.xrTableCell24.Name = "xrTableCell24";
            this.xrTableCell24.Text = "Cost Centre";
            this.xrTableCell24.Weight = 0.079690821559820657D;
            this.xrTableCell24.WordWrap = false;
            // 
            // xrTableCell25
            // 
            this.xrTableCell25.Name = "xrTableCell25";
            this.xrTableCell25.Text = "Hours";
            this.xrTableCell25.Weight = 0.064103354075624286D;
            this.xrTableCell25.WordWrap = false;
            // 
            // xrTableCell26
            // 
            this.xrTableCell26.Name = "xrTableCell26";
            this.xrTableCell26.Text = "State Employed";
            this.xrTableCell26.Weight = 0.091056611243450936D;
            this.xrTableCell26.WordWrap = false;
            // 
            // Occupation
            // 
            this.Occupation.Name = "Occupation";
            this.Occupation.Text = "Occupation";
            this.Occupation.Weight = 0.14971362885405454D;
            this.Occupation.WordWrap = false;
            // 
            // Location
            // 
            this.Location.Name = "Location";
            this.Location.Text = "Location";
            this.Location.Weight = 0.14785449175826188D;
            this.Location.WordWrap = false;
            // 
            // HECS
            // 
            this.HECS.Name = "HECS";
            this.HECS.Text = "HECS";
            this.HECS.Weight = 0.10099003122273406D;
            this.HECS.WordWrap = false;
            // 
            // Paym
            // 
            this.Paym.Name = "Paym";
            this.Paym.Text = "Personal Leave";
            this.Paym.Weight = 0.13944745576778647D;
            this.Paym.WordWrap = false;
            // 
            // Annu
            // 
            this.Annu.Name = "Annu";
            this.Annu.Text = "Annual Leave";
            this.Annu.Weight = 0.12248146722436246D;
            this.Annu.WordWrap = false;
            // 
            // Long
            // 
            this.Long.Name = "Long";
            this.Long.Text = "Long Service Leave";
            this.Long.Weight = 0.099727859497055232D;
            this.Long.WordWrap = false;
            // 
            // RDO
            // 
            this.RDO.Name = "RDO";
            this.RDO.Text = "RDO";
            this.RDO.Weight = 0.086642646633166454D;
            this.RDO.WordWrap = false;
            // 
            // EmployeeCode
            // 
            this.EmployeeCode.Name = "EmployeeCode";
            this.EmployeeCode.Text = "Employee Code";
            this.EmployeeCode.Weight = 0.172797315636587D;
            this.EmployeeCode.WordWrap = false;
            // 
            // Status
            // 
            this.Status.Name = "Status";
            this.Status.Text = "Status";
            this.Status.Weight = 0.11918043524338445D;
            this.Status.WordWrap = false;
            // 
            // xrTableCell1
            // 
            this.xrTableCell1.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell1.Name = "xrTableCell1";
            this.xrTableCell1.Text = "Email";
            this.xrTableCell1.Weight = 0.11017042679585767D;
            // 
            // HideEmergencyContactDetails
            // 
            this.HideEmergencyContactDetails.Condition = "[ShowEmergencyContactDetails] == False";
            this.HideEmergencyContactDetails.DataMember = "Employees";
            this.HideEmergencyContactDetails.Formatting.Visible = DevExpress.Utils.DefaultBoolean.False;
            this.HideEmergencyContactDetails.Name = "HideEmergencyContactDetails";
            // 
            // xrTableCell4
            // 
            this.xrTableCell4.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell4.Name = "xrTableCell4";
            this.xrTableCell4.Text = "HomePhone";
            this.xrTableCell4.Weight = 0.22337374267712848D;
            // 
            // xrTableCell3
            // 
            this.xrTableCell3.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell3.Name = "xrTableCell3";
            this.xrTableCell3.Text = "MobilePhone";
            this.xrTableCell3.Weight = 0.23145970403458321D;
            // 
            // xrTableCell5
            // 
            this.xrTableCell5.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell5.Name = "xrTableCell5";
            this.xrTableCell5.Text = "EmergencyName";
            this.xrTableCell5.Weight = 0.29884292591861616D;
            // 
            // xrTableCell2
            // 
            this.xrTableCell2.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell2.Name = "xrTableCell2";
            this.xrTableCell2.Text = "NextOfKinRelation";
            this.xrTableCell2.Weight = 0.33388147324593331D;
            // 
            // xrTableCell7
            // 
            this.xrTableCell7.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell7.Name = "xrTableCell7";
            this.xrTableCell7.Text = "EmergencyPhone";
            this.xrTableCell7.Weight = 0.32040527896658511D;
            // 
            // xrTableCell6
            // 
            this.xrTableCell6.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell6.Name = "xrTableCell6";
            this.xrTableCell6.Text = "EmergencyMobile";
            this.xrTableCell6.Weight = 0.33388198651496481D;
            // 
            // xrTableCell8
            // 
            this.xrTableCell8.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell8.Name = "xrTableCell8";
            this.xrTableCell8.Text = "EmergencyAddress1";
            this.xrTableCell8.Weight = 0.36504728340852216D;
            // 
            // xrTableCell9
            // 
            this.xrTableCell9.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell9.Name = "xrTableCell9";
            this.xrTableCell9.Text = "EmergencyAddress2";
            this.xrTableCell9.Weight = 0.20408586643497206D;
            // 
            // xrTableCell10
            // 
            this.xrTableCell10.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell10.Name = "xrTableCell10";
            this.xrTableCell10.Text = "EmergencyAddress3";
            this.xrTableCell10.Weight = 0.19143764816370706D;
            // 
            // xrTableCell21
            // 
            this.xrTableCell21.Name = "xrTableCell21";
            this.xrTableCell21.Text = "Department";
            this.xrTableCell21.Weight = 0.15453186758210227D;
            // 
            // DetailReport2
            // 
            this.DetailReport2.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.Detail3});
            this.DetailReport2.DataMember = "Employees";
            this.DetailReport2.DataSource = this.DDEmploeeBinding;
            this.DetailReport2.Level = 0;
            this.DetailReport2.Name = "DetailReport2";
            // 
            // Detail3
            // 
            this.Detail3.Controls.AddRange(new DevExpress.XtraReports.UI.XRControl[] {
            this.xrTable3});
            this.Detail3.HeightF = 25F;
            this.Detail3.Name = "Detail3";
            // 
            // xrTable3
            // 
            this.xrTable3.Borders = DevExpress.XtraPrinting.BorderSide.None;
            this.xrTable3.Font = new System.Drawing.Font("Arial", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.xrTable3.LocationFloat = new DevExpress.Utils.PointFloat(0F, 0F);
            this.xrTable3.Name = "xrTable3";
            this.xrTable3.Rows.AddRange(new DevExpress.XtraReports.UI.XRTableRow[] {
            this.xrTableRow3});
            this.xrTable3.SizeF = new System.Drawing.SizeF(2339F, 25F);
            this.xrTable3.StylePriority.UseBorders = false;
            this.xrTable3.StylePriority.UseFont = false;
            // 
            // xrTableRow3
            // 
            this.xrTableRow3.Cells.AddRange(new DevExpress.XtraReports.UI.XRTableCell[] {
            this.xrTableCell27,
            this.xrTableCell29,
            this.xrTableCell30,
            this.xrTableCell31,
            this.xrTableCell32,
            this.xrTableCell33,
            this.xrTableCell34,
            this.xrTableCell35,
            this.xrTableCell36,
            this.xrTableCell37,
            this.xrTableCell38,
            this.xrTableCell39,
            this.xrTableCell40,
            this.xrTableCell41,
            this.xrTableCell42,
            this.xrTableCell43,
            this.xrTableCell44,
            this.xrTableCell45,
            this.xrTableCell46,
            this.xrTableCell47,
            this.xrTableCell48,
            this.xrTableCell49,
            this.xrTableCell50,
            this.xrTableCell51,
            this.xrTableCell52,
            this.xrTableCell11,
            this.xrTableCell16,
            this.xrTableCell13,
            this.xrTableCell15,
            this.xrTableCell14,
            this.xrTableCell12,
            this.xrTableCell20,
            this.xrTableCell18,
            this.xrTableCell17,
            this.xrTableCell19,
            this.xrTableCell28,
            this.xrTableCell53});
            this.xrTableRow3.Name = "xrTableRow3";
            this.xrTableRow3.Weight = 1D;
            // 
            // xrTableCell27
            // 
            this.xrTableCell27.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.FamilyName")});
            this.xrTableCell27.Name = "xrTableCell27";
            this.xrTableCell27.Text = "xrTableCell27";
            this.xrTableCell27.Weight = 0.1303226814789534D;
            this.xrTableCell27.WordWrap = false;
            // 
            // xrTableCell29
            // 
            this.xrTableCell29.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.GivenName")});
            this.xrTableCell29.Name = "xrTableCell29";
            this.xrTableCell29.Text = "xrTableCell29";
            this.xrTableCell29.Weight = 0.10297821631115781D;
            this.xrTableCell29.WordWrap = false;
            // 
            // xrTableCell30
            // 
            this.xrTableCell30.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.MiddleName")});
            this.xrTableCell30.Name = "xrTableCell30";
            this.xrTableCell30.Text = "xrTableCell30";
            this.xrTableCell30.Weight = 0.13056754075991034D;
            this.xrTableCell30.WordWrap = false;
            // 
            // xrTableCell31
            // 
            this.xrTableCell31.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Gender")});
            this.xrTableCell31.Name = "xrTableCell31";
            this.xrTableCell31.Text = "xrTableCell31";
            this.xrTableCell31.Weight = 0.13962006862828374D;
            this.xrTableCell31.WordWrap = false;
            // 
            // xrTableCell32
            // 
            this.xrTableCell32.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.StreetAddress")});
            this.xrTableCell32.Name = "xrTableCell32";
            this.xrTableCell32.Text = "xrTableCell32";
            this.xrTableCell32.Weight = 0.10638827846359678D;
            this.xrTableCell32.WordWrap = false;
            // 
            // xrTableCell33
            // 
            this.xrTableCell33.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Suburb")});
            this.xrTableCell33.Name = "xrTableCell33";
            this.xrTableCell33.Text = "xrTableCell33";
            this.xrTableCell33.Weight = 0.1370416292336557D;
            this.xrTableCell33.WordWrap = false;
            // 
            // xrTableCell34
            // 
            this.xrTableCell34.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.State")});
            this.xrTableCell34.Name = "xrTableCell34";
            this.xrTableCell34.Text = "xrTableCell34";
            this.xrTableCell34.Weight = 0.099821150721146945D;
            this.xrTableCell34.WordWrap = false;
            // 
            // xrTableCell35
            // 
            this.xrTableCell35.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Postcode")});
            this.xrTableCell35.Name = "xrTableCell35";
            this.xrTableCell35.Text = "xrTableCell35";
            this.xrTableCell35.Weight = 0.17470662945167087D;
            this.xrTableCell35.WordWrap = false;
            // 
            // xrTableCell36
            // 
            this.xrTableCell36.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Birthdate", "{0:dd/MM/yyyy}")});
            this.xrTableCell36.Name = "xrTableCell36";
            this.xrTableCell36.Text = "xrTableCell36";
            this.xrTableCell36.Weight = 0.09164078842012742D;
            this.xrTableCell36.WordWrap = false;
            // 
            // xrTableCell37
            // 
            this.xrTableCell37.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.StartDate", "{0:dd/MM/yyyy}")});
            this.xrTableCell37.Name = "xrTableCell37";
            this.xrTableCell37.Text = "xrTableCell37";
            this.xrTableCell37.Weight = 0.093778506442438181D;
            this.xrTableCell37.WordWrap = false;
            // 
            // xrTableCell38
            // 
            this.xrTableCell38.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.TerminationDate", "{0:dd/MM/yyyy}")});
            this.xrTableCell38.Name = "xrTableCell38";
            this.xrTableCell38.Text = "xrTableCell38";
            this.xrTableCell38.Weight = 0.14801809809302796D;
            this.xrTableCell38.WordWrap = false;
            // 
            // xrTableCell39
            // 
            this.xrTableCell39.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.HourlyRate", "{0:$0.0000;($0.0000);\'\'} ")});
            this.xrTableCell39.Name = "xrTableCell39";
            this.xrTableCell39.StylePriority.UseTextAlignment = false;
            this.xrTableCell39.Text = "xrTableCell39";
            this.xrTableCell39.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            this.xrTableCell39.Weight = 0.1248123432026309D;
            this.xrTableCell39.WordWrap = false;
            // 
            // xrTableCell40
            // 
            this.xrTableCell40.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.PaymentGroup")});
            this.xrTableCell40.Name = "xrTableCell40";
            this.xrTableCell40.Text = "xrTableCell40";
            this.xrTableCell40.Weight = 0.14662596011379012D;
            this.xrTableCell40.WordWrap = false;
            // 
            // xrTableCell41
            // 
            this.xrTableCell41.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.CostCentreName", "{0:#,###.000;(#,###.000);\'\'}")});
            this.xrTableCell41.Name = "xrTableCell41";
            this.xrTableCell41.Text = "xrTableCell41";
            this.xrTableCell41.Weight = 0.079690821559820657D;
            this.xrTableCell41.WordWrap = false;
            // 
            // xrTableCell42
            // 
            this.xrTableCell42.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.CostCentreHours", "{0:0.000;(0.000);\'\'}")});
            this.xrTableCell42.Name = "xrTableCell42";
            this.xrTableCell42.Text = "xrTableCell42";
            this.xrTableCell42.Weight = 0.064103354075624286D;
            this.xrTableCell42.WordWrap = false;
            // 
            // xrTableCell43
            // 
            this.xrTableCell43.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.StateEmployed")});
            this.xrTableCell43.Name = "xrTableCell43";
            this.xrTableCell43.Text = "xrTableCell43";
            this.xrTableCell43.Weight = 0.091056611243450936D;
            this.xrTableCell43.WordWrap = false;
            // 
            // xrTableCell44
            // 
            this.xrTableCell44.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Occupation")});
            this.xrTableCell44.Name = "xrTableCell44";
            this.xrTableCell44.Text = "xrTableCell44";
            this.xrTableCell44.Weight = 0.14971362885405454D;
            this.xrTableCell44.WordWrap = false;
            // 
            // xrTableCell45
            // 
            this.xrTableCell45.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.PayLocation")});
            this.xrTableCell45.Name = "xrTableCell45";
            this.xrTableCell45.Text = "xrTableCell45";
            this.xrTableCell45.Weight = 0.14785449175826188D;
            this.xrTableCell45.WordWrap = false;
            // 
            // xrTableCell46
            // 
            this.xrTableCell46.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.HECSCal")});
            this.xrTableCell46.Name = "xrTableCell46";
            this.xrTableCell46.StylePriority.UseTextAlignment = false;
            this.xrTableCell46.Text = "xrTableCell46";
            this.xrTableCell46.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopCenter;
            this.xrTableCell46.Weight = 0.10099003122273406D;
            this.xrTableCell46.WordWrap = false;
            // 
            // xrTableCell47
            // 
            this.xrTableCell47.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.AccruedSL", "{0:#0.000}")});
            this.xrTableCell47.Name = "xrTableCell47";
            this.xrTableCell47.Text = "xrTableCell47";
            this.xrTableCell47.Weight = 0.13944745576778647D;
            this.xrTableCell47.WordWrap = false;
            // 
            // xrTableCell48
            // 
            this.xrTableCell48.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.AccruedAL", "{0:#0.000}")});
            this.xrTableCell48.Name = "xrTableCell48";
            this.xrTableCell48.Text = "xrTableCell48";
            this.xrTableCell48.Weight = 0.12248146722436246D;
            this.xrTableCell48.WordWrap = false;
            // 
            // xrTableCell49
            // 
            this.xrTableCell49.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.AccruedLSL", "{0:#0.000}")});
            this.xrTableCell49.Name = "xrTableCell49";
            this.xrTableCell49.Text = "xrTableCell49";
            this.xrTableCell49.Weight = 0.099727859497055232D;
            this.xrTableCell49.WordWrap = false;
            // 
            // xrTableCell50
            // 
            this.xrTableCell50.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.AccruedRDO", "{0:#0.000}")});
            this.xrTableCell50.Name = "xrTableCell50";
            this.xrTableCell50.Text = "xrTableCell50";
            this.xrTableCell50.Weight = 0.086642646633166454D;
            this.xrTableCell50.WordWrap = false;
            this.xrTableCell50.XlsxFormatString = "{0:0.0000;(0.0000);\'\'} ";
            // 
            // xrTableCell51
            // 
            this.xrTableCell51.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmployeeCode")});
            this.xrTableCell51.Name = "xrTableCell51";
            this.xrTableCell51.Text = "xrTableCell51";
            this.xrTableCell51.Weight = 0.172797315636587D;
            this.xrTableCell51.WordWrap = false;
            // 
            // xrTableCell52
            // 
            this.xrTableCell52.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmploymentStatus")});
            this.xrTableCell52.Name = "xrTableCell52";
            this.xrTableCell52.Text = "xrTableCell52";
            this.xrTableCell52.Weight = 0.11918032451692105D;
            this.xrTableCell52.WordWrap = false;
            // 
            // xrTableCell11
            // 
            this.xrTableCell11.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.Email")});
            this.xrTableCell11.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell11.Name = "xrTableCell11";
            this.xrTableCell11.Text = "xrTableCell11";
            this.xrTableCell11.Weight = 0.11017027592172403D;
            this.xrTableCell11.WordWrap = false;
            // 
            // xrTableCell16
            // 
            this.xrTableCell16.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.HomePhone")});
            this.xrTableCell16.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell16.Name = "xrTableCell16";
            this.xrTableCell16.Text = "xrTableCell16";
            this.xrTableCell16.Weight = 0.22337373492609014D;
            this.xrTableCell16.WordWrap = false;
            // 
            // xrTableCell13
            // 
            this.xrTableCell13.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.MobilePhone")});
            this.xrTableCell13.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell13.Name = "xrTableCell13";
            this.xrTableCell13.Text = "xrTableCell13";
            this.xrTableCell13.Weight = 0.23145938042567926D;
            this.xrTableCell13.WordWrap = false;
            // 
            // xrTableCell15
            // 
            this.xrTableCell15.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyName")});
            this.xrTableCell15.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell15.Name = "xrTableCell15";
            this.xrTableCell15.Text = "xrTableCell15";
            this.xrTableCell15.Weight = 0.29884323402544344D;
            this.xrTableCell15.WordWrap = false;
            // 
            // xrTableCell14
            // 
            this.xrTableCell14.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.NextOfKinRelation")});
            this.xrTableCell14.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell14.Name = "xrTableCell14";
            this.xrTableCell14.Text = "xrTableCell14";
            this.xrTableCell14.Weight = 0.33388134704819544D;
            this.xrTableCell14.WordWrap = false;
            // 
            // xrTableCell12
            // 
            this.xrTableCell12.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyPhone")});
            this.xrTableCell12.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell12.Name = "xrTableCell12";
            this.xrTableCell12.Text = "xrTableCell12";
            this.xrTableCell12.Weight = 0.32040527121554674D;
            this.xrTableCell12.WordWrap = false;
            // 
            // xrTableCell20
            // 
            this.xrTableCell20.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyMobile")});
            this.xrTableCell20.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell20.Name = "xrTableCell20";
            this.xrTableCell20.Text = "xrTableCell20";
            this.xrTableCell20.Weight = 0.33388197876392645D;
            this.xrTableCell20.WordWrap = false;
            // 
            // xrTableCell18
            // 
            this.xrTableCell18.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyAddress1")});
            this.xrTableCell18.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell18.Name = "xrTableCell18";
            this.xrTableCell18.Text = "xrTableCell18";
            this.xrTableCell18.Weight = 0.3650473584974695D;
            this.xrTableCell18.WordWrap = false;
            // 
            // xrTableCell17
            // 
            this.xrTableCell17.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyAddress2")});
            this.xrTableCell17.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell17.Name = "xrTableCell17";
            this.xrTableCell17.Text = "xrTableCell17";
            this.xrTableCell17.Weight = 0.20408586604257506D;
            this.xrTableCell17.WordWrap = false;
            // 
            // xrTableCell19
            // 
            this.xrTableCell19.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.EmergencyAddress3")});
            this.xrTableCell19.FormattingRules.Add(this.HideEmergencyContactDetails);
            this.xrTableCell19.Name = "xrTableCell19";
            this.xrTableCell19.Text = "xrTableCell19";
            this.xrTableCell19.Weight = 0.19143766237066445D;
            this.xrTableCell19.WordWrap = false;
            // 
            // xrTableCell28
            // 
            this.xrTableCell28.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.DepartmentName")});
            this.xrTableCell28.Name = "xrTableCell28";
            this.xrTableCell28.Weight = 0.15453219574702329D;
            // 
            // HECSCal
            // 
            this.HECSCal.DataMember = "Employees";
            this.HECSCal.Expression = "Iif( lower([HECS]) == \'true\',\'Y\'  ,\'N\' )";
            this.HECSCal.Name = "HECSCal";
            // 
            // HideEmergencyContactDetailsHeader
            // 
            this.HideEmergencyContactDetailsHeader.Condition = "[Employees.ShowEmergencyContactDetails] == false";
            this.HideEmergencyContactDetailsHeader.Name = "HideEmergencyContactDetailsHeader";
            // 
            // xrTableCell54
            // 
            this.xrTableCell54.Name = "xrTableCell54";
            this.xrTableCell54.Text = "Last Login Date";
            this.xrTableCell54.Weight = 0.28505380608628322D;
            // 
            // xrTableCell53
            // 
            this.xrTableCell53.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "Employees.LastLogin", "{0:dd/MM/yyyy hh:mm:ss}")});
            this.xrTableCell53.Name = "xrTableCell53";
            this.xrTableCell53.Text = "xrTableCell53";
            this.xrTableCell53.Weight = 0.2850541412753701D;
            // 
            // DDEmploeeBinding
            // 
            this.DDEmploeeBinding.DataSource = typeof(DDEmployee);
            // 
            // DDEmployeeReport
            // 
            this.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.Detail,
            this.TopMargin,
            this.BottomMargin,
            this.GroupHeader1,
            this.DetailReport2});
            this.CalculatedFields.AddRange(new DevExpress.XtraReports.UI.CalculatedField[] {
            this.HECSCal});
            this.DataSource = this.DDEmploeeBinding;
            this.ExportOptions.Xls.ShowGridLines = true;
            this.ExportOptions.Xlsx.ShowGridLines = true;
            this.FormattingRuleSheet.AddRange(new DevExpress.XtraReports.UI.FormattingRule[] {
            this.HideEmergencyContactDetails,
            this.HideEmergencyContactDetailsHeader});
            this.Landscape = true;
            this.Margins = new System.Drawing.Printing.Margins(0, 0, 0, 0);
            this.PageColor = System.Drawing.Color.Transparent;
            this.PageHeight = 1654;
            this.PageWidth = 2339;
            this.PaperKind = System.Drawing.Printing.PaperKind.A2;
            this.Version = "17.1";
            ((System.ComponentModel.ISupportInitialize)(this.xrTable2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.xrTable3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DDEmploeeBinding)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();

            (this.DataSource as ObjectDataSource).Fill();


        }

        #endregion

        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.XRTable xrTable2;
        private DevExpress.XtraReports.UI.XRTableRow xrTableRow2;
        private DevExpress.XtraReports.UI.XRTableCell FamilyName;
        private DevExpress.XtraReports.UI.XRTableCell GivenName;
        private DevExpress.XtraReports.UI.XRTableCell MiddleName;
        private DevExpress.XtraReports.UI.XRTableCell Gender;
        private DevExpress.XtraReports.UI.XRTableCell StreetAddress1;
        private DevExpress.XtraReports.UI.XRTableCell Suburb;
        private DevExpress.XtraReports.UI.XRTableCell State;
        private DevExpress.XtraReports.UI.XRTableCell Postcode;
        private DevExpress.XtraReports.UI.XRTableCell Birthdate;
        private DevExpress.XtraReports.UI.XRTableCell StartDate;
        private DevExpress.XtraReports.UI.XRTableCell TerminationDate;
        private DevExpress.XtraReports.UI.XRTableCell HourlyRate;
        private DevExpress.XtraReports.UI.XRTableCell Occupation;
        private DevExpress.XtraReports.UI.XRTableCell Location;
        private DevExpress.XtraReports.UI.XRTableCell HECS;
        private DevExpress.XtraReports.UI.XRTableCell Paym;
        private DevExpress.XtraReports.UI.XRTableCell Annu;
        private DevExpress.XtraReports.UI.XRTableCell Long;
        private DevExpress.XtraReports.UI.XRTableCell RDO;
        private DevExpress.XtraReports.UI.XRTableCell EmployeeCode;
        private DevExpress.XtraReports.UI.XRTableCell Status;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell23;
        private ObjectDataSource DDEmploeeBinding;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport2;
        private DevExpress.XtraReports.UI.DetailBand Detail3;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell22;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell24;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell25;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell26;
        private DevExpress.XtraReports.UI.XRTable xrTable3;
        private DevExpress.XtraReports.UI.XRTableRow xrTableRow3;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell27;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell29;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell30;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell31;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell32;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell33;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell34;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell35;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell36;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell37;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell38;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell39;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell40;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell41;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell42;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell43;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell44;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell45;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell46;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell47;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell48;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell49;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell50;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell51;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell52;
        private DevExpress.XtraReports.UI.CalculatedField HECSCal;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell1;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell4;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell3;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell5;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell2;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell7;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell6;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell8;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell9;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell10;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell11;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell16;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell13;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell15;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell14;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell12;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell20;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell18;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell17;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell19;
        private DevExpress.XtraReports.UI.FormattingRule HideEmergencyContactDetails;
        private DevExpress.XtraReports.UI.FormattingRule HideEmergencyContactDetailsHeader;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell21;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell28;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell54;
        private DevExpress.XtraReports.UI.XRTableCell xrTableCell53;
    }
}
